# 1.Math

In [1]:
'''
Sometimes we have to perform mathematical tasks on numbers i.e. minimum, maximum,
 sqrt, ceil.,floor, pi etc.
'''

'\nSometimes we have to perform mathematical tasks on numbers i.e. minimum, maximum,\n sqrt, ceil.,floor, pi etc.\n'

In [2]:
a=(1,2,3,4)
b=[4,3,5,7]
print(min(a))
print(max(b))

1
7


In [3]:
'''
absolute (positive) value of the spacified number
'''
a=-65
print(abs(a))

65


In [4]:
'''
power of a number
'''
a=pow(3,4)   #3**4
print(a)

81


In [5]:
'''
For some extended mathemaical function, please import math first
'''
import numpy as np

In [6]:
x=np.sqrt(64)
x

8.0

In [7]:
'''ceil or floor'''
x=5.000001
print(np.ceil(x))
print(np.floor(x))

6.0
5.0


In [8]:
x=np.pi+6
x

9.141592653589793

# 2.File handling

## 2.1 Create/write a file

In [9]:
import numpy as np

In [10]:
#To create a new file in Python, use the open() method
file = open("my_file.txt", "w")


In [11]:
file = open("my_file.txt", "w")
file.write("This is my first text file")
file.close()

In [12]:
#Open a Text file and write some 1-D arrays 

In [13]:
a=np.array([[1],[2],[3],[4],[5],[6]])

In [14]:
a_file = open("test.txt", "w")
for row in a:
    np.savetxt(a_file, row)
a_file.close()

In [15]:
# Single Line statement to save datapoints 
a=np.array([1,2,3,4])
np.savetxt("test.txt", a)

In [16]:
aa=np.array([1,2,3,4,5])
bb=np.array([1,2,3,4,5])
np.savetxt("tt.txt", (aa,bb))
# np.savetxt("testt.txt", np.transpose([a,b]))



In [17]:
# Add header to Text File
x=np.linspace(0,1,10)
y=np.sin(x)
np.savetxt("testt.txt", np.transpose([x,y]), fmt="%f",delimiter=" ", newline="\n",header='hhh')


In [18]:
# Add footer to Text File

x=np.linspace(0,1,10)
y=np.sin(x)
np.savetxt("testt.txt", np.transpose([x,y]), fmt="%f",delimiter=" ", newline="\n",header='hhh', footer='ff')


In [19]:
'''
"x" - Create - will create a file, returns an error if the file exist

"a" - Append - will create a file if the specified file does not exist

"w" - Write - will create a file if the specified file does not exist 

 The "w" method will overwrite the entire file.
'''

'\n"x" - Create - will create a file, returns an error if the file exist\n\n"a" - Append - will create a file if the specified file does not exist\n\n"w" - Write - will create a file if the specified file does not exist \n\n The "w" method will overwrite the entire file.\n'

In [21]:
f = open("testt.txt", "x")

FileExistsError: ignored

## 2.2 Read a File

In [22]:
f = open("testt.txt", "r")    #will see the way to define its location

In [23]:
f = open("testt.txt", "r")    #will see the way to define its location
print(f.read())
f.close()


# hhh
0.000000 0.000000
0.111111 0.110883
0.222222 0.220398
0.333333 0.327195
0.444444 0.429956
0.555556 0.527415
0.666667 0.618370
0.777778 0.701698
0.888889 0.776372
1.000000 0.841471
# ff



In [24]:
# read text file using loadtxt
f= np.loadtxt("testt.txt")

In [25]:
f

array([[0.      , 0.      ],
       [0.111111, 0.110883],
       [0.222222, 0.220398],
       [0.333333, 0.327195],
       [0.444444, 0.429956],
       [0.555556, 0.527415],
       [0.666667, 0.61837 ],
       [0.777778, 0.701698],
       [0.888889, 0.776372],
       [1.      , 0.841471]])

In [26]:
f[0]

array([0., 0.])

In [27]:
# read text file using loadtxt
f= np.loadtxt("testt.txt",unpack="True")

In [28]:
f

array([[0.      , 0.111111, 0.222222, 0.333333, 0.444444, 0.555556,
        0.666667, 0.777778, 0.888889, 1.      ],
       [0.      , 0.110883, 0.220398, 0.327195, 0.429956, 0.527415,
        0.61837 , 0.701698, 0.776372, 0.841471]])

In [29]:
f[0]

array([0.      , 0.111111, 0.222222, 0.333333, 0.444444, 0.555556,
       0.666667, 0.777778, 0.888889, 1.      ])

## 2.3 Delete a File

In [30]:
#Now to delete a file or folder you have to interact with the operating system

#The OS module in Python provides functions for interacting with the operating system

# The OS module in Python provides functions for creating and removing a directory 
#(folder), fetching its contents, changing and identifying the current directory, etc.

In [31]:
import os
os.remove("my_file.txt")

# --->Next Session will includes<---
## -->Mathplotlib
## -->Install Python Modules
## --> Pandas