# 1.List, Tuple, Set and Dictionaries

## 1.1 List (or Array)

### 1.1.1 Basics

In [ ]:
x=[] # Define an empty list
x

[]

In [ ]:
y=[1,2,3,5,4,5,6,9] #Define a list of numbers
y

[1, 2, 3, 5, 4, 5, 6, 9]

In [ ]:
y[::-1] # Reverse the list

[9, 6, 5, 4, 5, 3, 2, 1]

In [ ]:
z=['Apple','Boy','Cat']  #Define a list of string
z

['Apple', 'Boy', 'Cat']

In [ ]:
len(y) # Check the length of list

3

In [ ]:
z[-1]

'Cat'

In [ ]:
m=['Apple','Boy','Cat',[1,2]] # Define a list of objects with different data types
m[0][1], m[2][2], m[3][0] #Output: 'p','t',1


('p', 't', 1)

### 1.1.2 Positions & Modify element in list

In [ ]:
y=[1,2,3,4,5,6,7] #Define a list of numbers

In [ ]:
y[2]  #Print an element or number of specific position

3

In [ ]:
y[-1]

7

In [ ]:
y[0:2]    #Print first two elements

[1, 2]

In [ ]:
y[2:4]    #Print elements from 2nd position to 4th position

[4]

In [ ]:
y=[1,2,3] #Define a list of numbers
y[2]=4
y

[1, 2, 4]

In [ ]:
'''
Add List Items
'''
y=[1,2,3,4,5]
y.append(8)
print(y)

[1, 2, 3, 4, 5, 8]


In [ ]:
'''
insert item at a particular position
'''
y=[1,2,3,4,5]
y.insert(1,8)
print(y)

[1, 8, 2, 3, 4, 5]


In [ ]:
'''
Extend List
'''
x=[1,2,3,4]
y=[5,6,7,8]
x.extend(y)
print(x)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
'''
Remove Items from a list
'''
y=[1,3,4,7,8]
y.remove(3)       #Try to remove an unlisted item--Error? Its okay!
print(y)

[1, 4, 7, 8]


In [ ]:
'''
Remove Specified Index use: pop
'''
y=[1,3,4,7,8]
y.pop(2)    #y.del(2)
print(y)

[1, 3, 7, 8]


In [ ]:
'''
Remove Specified Index use: del
'''
y=[1,3,4,7,8]
del y[2] 
print(y)

[1, 3, 7, 8]


In [ ]:
'''
Remove a list completely
'''
y=[1,3,4,7,8]
del y        # expected output []
print(y)     #this will cause an error because you have succsesfully deleted "y".

NameError: ignored

In [ ]:
'''
Clear a list
'''
y=[1,3,4,7,8]
y.clear()
print(y)    

[]


## 1.2 Tuples

In [ ]:
'''
they’re immutable sequences. This means that you can’t change them after creation.
Tuple items are ordered, unchangeable, and allow duplicate values. 
To create a tuple object, can use an assignment operation with a sequence of a 
comma-separated items on its right side.
'''

'\nthey’re immutable sequences. \nTuple items are ordered, unchangeable, and allow duplicate values.\n\n'

In [ ]:
x=('Apple','Boy','Cat','Dog')

In [ ]:
x[2]='Fox'  #try to modify the Tuples

TypeError: ignored

In [ ]:
'''
Check type
'''
x=('Apple','Boy','Cat','Dog')
type(x)

tuple

In [ ]:
x=('Apple')   #if a single item in a Tuples
type(x)

str

In [ ]:
x=('Apple',)
type(x)

tuple

## 1.3 Sets

In [ ]:
'''
Set items are unordered, unchangeable, and do not allow duplicate values.
'''
x={'Apple','Boy','Cat','Dog'}
x[2]='fox'

TypeError: ignored

In [ ]:
x={'Apple','Boy','Cat','Dog','Boy'}
print(x)


{'Cat', 'Boy', 'Apple', 'Dog'}


In [ ]:
type(x)

set

## 1.4 Dictionaries

In [ ]:
'''
Dictionary items are ordered, changeable, and does not allow duplicates.
Dictionary items are presented in key:value pairs, and can be referred to by using the key name.
'''
India={"Name":"India","Continents":"Asia","Capital":"New Delhi"}
prsn=dict(Name="XYZ",Age="20",Height="170cm",Weight="70kg")
India, prsn

({'Capital': 'New Delhi', 'Continents': 'Asia', 'Name': 'India'},
 {'Age': '20', 'Height': '170cm', 'Name': 'XYZ', 'Weight': '70kg'})

In [ ]:
India["Name"], India["Capital"], prsn["Name"], prsn["Weight"]

('India', 'New Delhi', 'XYZ', '70kg')

In [ ]:
'''
List is a collection which is ordered and changeable. Allows duplicate members.
Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
Set is a collection which is unordered and unindexed. No duplicate members.
Dictionary is a collection which is ordered and changeable. No duplicate members.
'''

'\nList is a collection which is ordered and changeable. Allows duplicate members.\nTuple is a collection which is ordered and unchangeable. Allows duplicate members.\nSet is a collection which is unordered and unindexed. No duplicate members.\nDictionary is a collection which is ordered and changeable. No duplicate members.\n'

# 2.Vector and Matrix

In [ ]:
'''
Now we are going to discuss vectors, matrices and Multidimentional Arrays
'''
import numpy

## 2.1 Vectors

In [ ]:
import numpy
x=numpy.array([1,2,3])   #a vector as a row
x

array([1, 2, 3])

In [ ]:
y=numpy.array([[1],
              [2],
              [3]])   #a vector as a column
y

array([[1],
       [2],
       [3]])

In [ ]:
import numpy
x_row=numpy.array([1,2,3])
y_col=numpy.array([[1],[2],[3]]) 
'''
why should I type numpy every time
'''
import numpy as np
x_row=np.array([1,2,3])
y_col=np.array([[1],[2],[3]]) 

## 2.2 Matrix

In [ ]:
m=np.array([[1,2,3],
            [4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m.shape

(2, 3)

In [ ]:
'''
NumPy actually has a dedicated matrix data structure:
'''
mat=np.mat([[1,2,3],
            [4,5,6]])
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
mat.shape

(2, 3)

In [ ]:
m.size

9

In [ ]:
m.ndim


2

In [ ]:
'''
Selecting Elements
'''
vec=numpy.array([1,2,3,4,5,6,7])
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [ ]:
vec[1]   # Select second element of vector

2

In [ ]:
# Select second row, third column
m[1,2]

6

In [ ]:
vec=np.array((1,2,3,4,5))

In [ ]:
# Select all elements of a vector
vec[:]

array([1, 2, 3, 4, 5])

In [ ]:
# Select everything up to and including the fourth element
vec[:4]

array([1, 2, 3, 4])

In [ ]:
# Select everything after the fourth element
vec[4:]

array([5])

In [ ]:
# Select the last element
vec[-1]

5

In [ ]:
# Select the first two rows and all columns of a matrix
m[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Select all rows and the second column
m[:,1:2]

array([[2],
       [5],
       [8]])

## 2.3 Maximum & Minimum values

In [ ]:
'''
Finding the Maximum and Minimum Values
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
np.max(m), np.min(m)

(9, 1)

In [ ]:
'''
Finding the Maximum and Minimum Values from the each axis
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
np.max(m,axis=1)    #axis=0 max in each column & axis=1 max in each row

array([3, 6, 9])

## 2.4 Reshaping the array

In [ ]:
import numpy as np
m=np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]
             ])
m.shape

(4, 3)

In [ ]:
m_=m.reshape(2,6)
m_

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
m_.shape

(2, 6)

In [ ]:
# Reshape it as a 1-D array
m__=m_.reshape(12)
m__

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
m__.shape

(12,)

In [ ]:
m.resize(2,6)

In [ ]:
m

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
'''
reshape() does not changes the original array but only returns the changed array, 
whereas the resize() method returns nothing and directly changes the original array.
'''

## 2.5 Transpose, Rank, Determinant, Diagonal,trace and inverse of a matrix

In [ ]:
'''
Transpose
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]
            ])
m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
'''
Rank
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]
            ])
np.linalg.matrix_rank(m)      #linear algebra 

2

In [ ]:
'''
Determinant
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,1,9]
            ])
np.linalg.det(m)

-42.00000000000001

In [ ]:
'''
Diagonal
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,1,9]
            ])
m.diagonal()


array([1, 5, 9])

In [ ]:
# Return diagonal one above the main diagonal
m.diagonal(offset=1)

array([2, 6])

In [ ]:
# Return diagonal one below the main diagonal
m.diagonal(offset=-1)

array([4, 1])

In [ ]:
'''
Trace
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,1,9]
            ])
m.trace()           # OR sum(m.diagonal())

15

In [ ]:
'''
Inverse
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,1,9]
            ])
np.linalg.inv(m)


array([[-0.92857143,  0.35714286,  0.07142857],
       [-0.14285714,  0.28571429, -0.14285714],
       [ 0.73809524, -0.30952381,  0.07142857]])

## 2.6 Eigenvalues and Eigenvectors, addition, subtraction,dot product of two matrices.

In [ ]:
'''
Eigenvalues and Eigenvectors
'''
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]
            ])
e_values,e_vectors=np.linalg.eig(m)

In [ ]:
e_values,e_vectors

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [ ]:
'''
Addition of two matrices
'''
m_a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]
            ])
m_b=np.array([[0,2,1],
            [4,1,3],
            [7,2,6]
            ])
np.add(m_a,m_b)     # m_ab=m_a+m_b

array([[ 1,  4,  4],
       [ 8,  6,  9],
       [14, 10, 15]])

In [ ]:
'''
Substraction of two matrices
'''
m_a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]
            ])
m_b=np.array([[0,2,1],
            [4,1,3],
            [7,2,6]
            ])
np.subtract(m_a,m_b)     # m_ab=m_a+m_b

array([[1, 0, 2],
       [0, 4, 3],
       [0, 6, 3]])

In [ ]:
'''
Multiplication or dot product of two matrices
'''
m_a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]
            ])
m_b=np.array([[0,2,1],
            [4,1,3],
            [7,2,6]
            ])
np.dot(m_a,m_b)    

array([[29, 10, 25],
       [62, 25, 55],
       [95, 40, 85]])

In [ ]:
'''
Alternatively, in Python 3.5+, operator @ will also work for mulitplication
'''
m_a@m_b

array([[29, 10, 25],
       [62, 25, 55],
       [95, 40, 85]])

In [ ]:
'''
For elementwise multiplications of two matrices
'''
m_a*m_b

array([[ 0,  4,  3],
       [16,  5, 18],
       [49, 16, 54]])