# Import Packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

#Random Number Operations

## Random Items from list, tuple \& string

In [2]:
list=[0,2,4,6,8]
string="cosmology"
tuple=('Astronomy', 'Astrophysics', 'Cosmology', 'Dark Energy', 'Dark Matter')  

In [3]:
print(random.choice(list))

2


In [4]:
print(random.choice(string))

o


In [5]:
print(random.choice(tuple))

Cosmology


In [6]:
random.random()

0.837190274378118

## Random Shuffle

In [7]:
random.shuffle(list)  #shuffle will only work in list-->It changes the original list
print(list)

[4, 6, 8, 2, 0]


##Random Sampling

In [8]:
list=[0,2,4,6,8]
random.sample(list,3) #return a particluar list of items without any chnage in origi list

[8, 0, 2]

## Generate Random Numbers

In [9]:
print(random.randint(0,5))  #Generate a Random Number

4


In [10]:
print([random.randint(0,10) for i in range(5)]) #Generate a list of Random Number List

[1, 0, 4, 1, 2]


In [11]:
#Alternatively, for Random number list, you can use numpy as
np.random.randint(0,10,5)

array([1, 9, 6, 7, 0])

In [12]:
np.random.randint(0,10,size=5) #Basically the last arguments denotes the size of list

array([5, 0, 3, 1, 3])

In [13]:
np.random.randint(0,10,size=(2,5))

array([[9, 8, 1, 6, 6],
       [8, 7, 9, 6, 0]])

In [14]:
#Suppose you want to generate random floating values using randint
np.random.randint(0,10,size=(2,5)).astype("float")/10

array([[0.5, 0.3, 0.4, 0. , 0.4],
       [0.1, 0. , 0.5, 0. , 0. ]])

In [15]:
#Alternatively, one can use random_sample
np.random.random_sample(size=(2,5))

array([[0.82439903, 0.39924671, 0.49095907, 0.41336689, 0.92955337],
       [0.93804929, 0.03275835, 0.89094834, 0.01740002, 0.71608271]])